In [17]:
import jax  # noqa: F401
import jax.numpy as jnp

x = jnp.arange(5)
w = jnp.array([2., 3., 4.])


def convolve(x, w):
    output = []
    for i in range(len(x) - len(w) + 1):
        print(f"{x[i:i + len(w)]} * {w} = {jnp.dot(x[i:i + len(w)], w)}")
        output.append(jnp.dot(x[i:i + len(w)], w))
    return jnp.array(output)


convolve(x, w)

[0 1 2] * [2. 3. 4.] = 11.0
[1 2 3] * [2. 3. 4.] = 20.0
[2 3 4] * [2. 3. 4.] = 29.0


Array([11., 20., 29.], dtype=float32)

In [18]:
xs = jnp.stack([x, x])
ws = jnp.stack([w, w])


def manually_batched_convolve(xs, ws):
    output = [convolve(xs[i], ws[i]) for i in range(len(xs))]
    return jnp.stack(output)


manually_batched_convolve(xs, ws)

[0 1 2] * [2. 3. 4.] = 11.0
[1 2 3] * [2. 3. 4.] = 20.0
[2 3 4] * [2. 3. 4.] = 29.0
[0 1 2] * [2. 3. 4.] = 11.0
[1 2 3] * [2. 3. 4.] = 20.0
[2 3 4] * [2. 3. 4.] = 29.0


Array([[11., 20., 29.],
       [11., 20., 29.]], dtype=float32)